/**
 * Central place for every outbound/asset URL.
 *
 * Why this exists: the site ships to two hosts.
 *   - Vercel / local  → served from "/"
 *   - GitHub Pages    → served from "/react-19-persian-guide"
 *
 * `next/link` and `next/image` prefix basePath automatically, but a plain
 * <a href="/pdf/..."> or a raw <img> does NOT. Use `asset()` for those so a
 * download link never 404s on Pages.
 */
const BASE = process.env.NEXT_PUBLIC_BASE_PATH ?? "";

/** Prefix a public/ asset with the active basePath. */
export function asset(path: string): string {
  const clean = path.startsWith("/") ? path : `/${path}`;
  return `${BASE}${clean}`;
}

/** Canonical origin of the published site. */
export const SITE_URL = "https://rezaian-dev.github.io/react-19-persian-guide";

/** The online edition (generated by src/tools/build_reader.py, lives in public/book/). */
export const BOOK_URL = asset("/book/");

/** Deep-link to a single chapter inside the online edition. */
export function chapterUrl(n: number): string {
  return `${BOOK_URL}#ch-${String(n).padStart(2, "0")}`;
}

export const PDF_URL = asset("/pdf/React19-Persian-Guide.pdf");
export const EPUB_URL = asset("/pdf/React19-Persian-Guide.epub");

export const REPO_URL = "https://github.com/rezaian-dev/react-19-persian-guide";
export const ISSUES_URL = `${REPO_URL}/issues`;
export const AUTHOR_URL = "https://github.com/rezaian-dev";
